name: Aikido

on:
  workflow_call:
    secrets:
      AIKIDO_SECRET_KEY:
        required: true
        
jobs:
  aikido-security:
    name: aikidoSecurity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect new vulnerabilities
        uses: AikidoSec/github-actions-workflow@v1.0.12
        with:
            secret-key: ${{ secrets.AIKIDO_SECRET_KEY }}
            fail-on-timeout: true
            fail-on-dependency-scan: true
            fail-on-sast-scan: false
            fail-on-iac-scan: false
            minimum-severity: 'CRITICAL'
            timeout-seconds: 180
            post-scan-status-comment: true
            github-token: ${{ secrets.GITHUB_TOKEN }}
