name: .NET

on:
  workflow_call:
  
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['2.1.x', '3.1.x', '5.0.x', '6.0.x', '7.0.x', '8.0.x']

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --logger "GitHubActions;summary.includePassedTests=true;summary.includeSkippedTests=true" --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

  # build-windows:
  #   runs-on: windows-latest

  #   strategy:
  #     matrix:
  #       dotnet-version: ['2.1.x', '3.1.x', '5.0.x', '6.0.x', '7.0.x']

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Setup .NET
  #       uses: actions/setup-dotnet@v3
  #       with:
  #         dotnet-version: ${{ matrix.dotnet-version }}

  #     - name: Restore dependencies
  #       run: dotnet restore

  #     - name: Build
  #       run: dotnet build --configuration Release --no-restore

  #     - name: Test
  #       run: dotnet test --configuration Release --logger "GitHubActions;summary.includePassedTests=true;summary.includeSkippedTests=true" --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

  build-macos:
    runs-on: macOS-latest

    strategy:
      matrix:
        dotnet-version: ['2.1.x', '3.1.x', '5.0.x', '6.0.x', '7.0.x', '8.0.x']

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --logger "GitHubActions;summary.includePassedTests=true;summary.includeSkippedTests=true" --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

  results:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Final Results
    needs: [build-ubuntu, build-macos]
    steps:
    - run: exit 1
      if: >-
        ${{
             contains(needs.*.result, 'failure')
          || contains(needs.*.result, 'cancelled')
        }}
